apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: $SERVER
  name: externalCluster
contexts:
- context:
    cluster: externalCluster
    user: user
  name: external
current-context: external
kind: Config
preferences: {}
users:
- name: user
  user:
    client-certificate-data: $CLIENT_CERTIFICATE_DATA
    client-key-data: $CLIENT_KEY_DATA
